name: bank_feed_vs1
description: "A new Flutter project."
publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1

environment:
  sdk: ^3.5.3
dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  permission_handler: ^11.3.1
  english_words: ^4.0.0
  provider: ^6.0.0
  http: ^1.2.2
  intl: ^0.17.0
  animated_splash_screen: ^1.3.0
  lottie: ^3.1.3
  shared_preferences: ^2.3.2
  floor: ^1.5.0
  device_info_plus: ^11.1.0
  flutter_appauth: ^8.0.0+1
  loading_animation_widget: ^1.3.0
  page_transition: ^2.1.0
  flutter_launcher_icons: ^0.14.1
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  build_runner: ^2.1.2
  flutter_launcher_icons: "^0.14.1"

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: 
    - assets/BankFeed.png
flutter:
  uses-material-design: true
  assets:
    - assets/animations/
